name: CI

on:
   push:
      branches:
         - master

jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: '14'

         - name: Install dependencies
           run: npm install

         - name: Install Jest
           run: npm install --save-dev jest supertest @babel/preset-env @babel/core babel-jest

         - name: Run tests
           run: npm test
